.TH BURROW 1 "17 Mar 2018" "version 1.3.3"
.SH NAME
burrow \- a helper for building and managing a gopher hole
.SH SYNOPSIS
burrow [options] [command]
.SH DESRIPTION
burrow is a collection of helper actions designed to assist in the creation,
modification, and maintenance of a gopher hole.
.SH COMMANDS
.TP
.B phlog
Create a new phlog entry.
.TP
.B recipe
Add or update a recipe to the recipe box.
.B topic
Add or update a topic in your topics directory.
.TP
.B create-config
Generates a default configuration file at
.I ~/.config/burrow/config
if no other configuration file exists. It is populated with the default
settings.
.TP
.B edit-config
Opens your burrow configuration file for editing if it exists.
.TP
.B update-git
If the gopher directory resides within a git repository, this action will do a
silent
.B git-pull
which is useful for crons.
.TP
.B update-burrow
Burrow will attempt to auto-update. If the local folder where burrow is
installed is a git repository, burrow will pull the latest commit from the
remote branch. If the local directory is not a git remote, burrow will attempt
to update local files with their counterpart on the Github remote repository.
The local directory will only attempt to update files in this way which are
named
.I burrow
or some variation of that name.
.SH OPTIONS
.TP
.B -v, --version
Display current version information.
.TP
.B -d, --debug
Debug mode.
.TP 
.B -h, --help
Show the help.
.SH FILES
.I ~/.config/burrow/config
, 
.I ~/.config/burrow
, 
.I ~/.burrow
: configuration settings for burrow. If none of these are available, the default
configuration is loaded.
.SH BUGS
None known.
.SH AUTHOR
James Tomasino <tomasino (at) sdf (dot) org>
